### ISSUE TITLE
Bug in Webpage. Creators face can't be seen clearly.

### ISSUE THREAD

**Issue by chirag828049** [sidkhuntia/about#1]
The creators face can't be seen clearly. If it is meant to hide identity then please make it look visually better. 

![image](https://user-images.githubusercontent.com/75582834/117279324-3ba9de80-ae7f-11eb-85af-83ed61c6daa3.png)

**Comment by sidkhuntia** [comment]
That is my first attempt and it is not responsive so it will get disturbed if u zoom or use small viewport.

**Comment by chirag828049** [comment]
Ok. mate!
